apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres-shine-workflows
  name: postgres-service
  namespace: shine-workflows
spec:
  clusterIP: None
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    service: postgres-shine-workflows
