apiVersion: v1
kind: Secret
metadata:
  namespace: shine-workflows
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "mp"
  POSTGRES_PASSWORD: "PepperPåBiffen24!"
  POSTGRES_DB: "shine-workflows"
  POSTGRES_NON_ROOT_USER: "user"
  POSTGRES_NON_ROOT_PASSWORD: "superSecretPasswordMan!"
