apiVersion: v1
kind: Service
metadata:
  labels:
    service: shine-workflows
  name: shine-workflows
  namespace: shine-workflows
spec:
  type: LoadBalancer
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
      protocol: TCP
  selector:
    service: shine-workflows
