apiVersion: v1
kind: Service
metadata:
  name: shine-workflows-service
spec:
  type: LoadBalancer   # or NodePort if preferred
  selector:
    app: shine-workflows
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
