apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: shine-workflows-claim0
  name: shine-workflows-claim0
  namespace: shine-workflows
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
