apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: shine-workflows
  name: shine-workflows
  namespace: shine-workflows
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shine-workflows
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: shine-workflows
    spec:
      imagePullSecrets:
        - name: azure-cr-secret
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown 1000:1000 /data"]
          volumeMounts:
            - name: shine-workflows-claim0
              mountPath: /data
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres-service.shine-workflows.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
          image: shinekubernetesclusterregistry.azurecr.io/image-workflow-1741179359433:0.0.6
          imagePullPolicy: Always
          name: shine-workflows
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - mountPath: /home/node/.shine-workflows
              name: shine-workflows-claim0
      restartPolicy: Always
      volumes:
        - name: shine-workflows-claim0
          persistentVolumeClaim:
            claimName: shine-workflows-claim0
        - name: shine-workflows-secret
          secret:
            secretName: shine-workflows-secret
        - name: postgres-secret
          secret:
            secretName: postgres-secret
